# Generated by Django 3.2.13 on 2022-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('type_id', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
